name: "Wirenboard Fast Modbus to MQTT"
description: "Hi, Mark!"
version: "0.342"
slug: "ha-wb-fast-modbus-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
options:
  Serial port config:
    - Port: ""
      # Baudrate: "9600"
      # Parity: "N"
      # Stop bit count: "2"
  # MQTT data:
  #   Host: "core-mosquitto"
  #   Port: 1883
  #   Username: ""
  #   Password: ""
schema:
  Serial port config:
    - Port: device(subsystem=tty)
      # Baudrate: list(1200|2400|4800|9600|19200|38400|57600|115200)
      # Parity: "list(N|O|E)"
      # Stop bit count: "list(1|2)"
  # MQTT data:
  #   Host: str
  #   Port: port
  #   Username: str
  #   Password: str
