name: "Wirenboard Fast Modbus"
description: "Web UI for Wirenboard Fast Modbus devices"
version: 0.42.1
slug: "ha-wb-fast-modbus-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
webui: http://[HOST]:[PORT:8080]
ingress: true
ingress_port: 8080
panel_icon: mdi:serial-port
options:
  Serial port config:
    - Port: ""
  # MQTT data:
  #   Host: "core-mosquitto"
  #   Port: 1883
  #   Username: ""
  #   Password: ""
schema:
  Serial port config:
    - Port: str
  # MQTT data:
  #   Host: str
  #   Port: port
  #   Username: str
  #   Password: str
