[project]
name = "ha-wb-fast-modbus-mqtt"
version = "0.42.2"
description = "Web UI with Wirenboard Fast Modbus protocol support"
authors = [
    {name = "Egor Smolencev", email = "oxygen1u8@mail.ru"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.136.0,<0.137.0)",
    "uvicorn (>=0.45.0,<0.46.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "alembic (>=1.18.4,<2.0.0)",
    "aiofiles (>=25.1.0,<26.0.0)",
    "pydantic (>=2.13.3,<3.0.0)",
    "pymodbus (>=3.13.0,<4.0.0)",
    "pyserial (>=3.5,<4.0)",
    "greenlet (>=3.4.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
