"""Remove unused columns

Revision ID: 040ec586f8c3
Revises:
Create Date: 2026-04-18 11:16:31.335367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "040ec586f8c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=10), nullable=False),
        sa.Column("serial_num", sa.Integer(), nullable=False),
        sa.Column("baudrate", sa.Integer(), nullable=False),
        sa.Column("parity", sa.String(length=1), nullable=False),
        sa.Column("bus_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bus_id"],
            ["bus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    op.drop_table("bus")
    # ### end Alembic commands ###
