"""Add slave_address field to devices table

Revision ID: 29a9f122a087
Revises: 9c6c9211132f
Create Date: 2026-04-18 17:31:58.627971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29a9f122a087"
down_revision: Union[str, Sequence[str], None] = "9c6c9211132f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slave_address", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("slave_address")

    # ### end Alembic commands ###
