"""remove device table; add modbus config table

Revision ID: 70c32aeede83
Revises: c66a10104ead
Create Date: 2026-07-09 16:31:07.100854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c32aeede83'
down_revision: Union[str, Sequence[str], None] = 'c66a10104ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modbus_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.CheckConstraint('json_valid(config)', name='ck_devices_config_json_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slave_address', sa.INTEGER(), nullable=False),
    sa.Column('serial_num', sa.INTEGER(), nullable=False),
    sa.Column('baudrate', sa.INTEGER(), nullable=False),
    sa.Column('parity', sa.VARCHAR(length=1), nullable=False),
    sa.Column('bus_id', sa.INTEGER(), nullable=False),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('itf_name', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_num')
    )
    op.drop_table('modbus_config')
    # ### end Alembic commands ###
