"""Add Bus and Device tables

Revision ID: 902b3ccc9cfc
Revises:
Create Date: 2026-04-19 08:16:50.428744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "902b3ccc9cfc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("baudrate", sa.JSON(), nullable=False),
        sa.Column("parity", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=10), nullable=False),
        sa.Column("slave_address", sa.Integer(), nullable=False),
        sa.Column("serial_num", sa.Integer(), nullable=False),
        sa.Column("baudrate", sa.Integer(), nullable=False),
        sa.Column("parity", sa.String(length=1), nullable=False),
        sa.Column("bus_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bus_id"],
            ["bus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_num"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("devices")
    op.drop_table("bus")
    # ### end Alembic commands ###
