"""Add templates table

Revision ID: 92acb144340a
Revises: 902b3ccc9cfc
Create Date: 2026-05-24 20:18:21.456550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92acb144340a"
down_revision: Union[str, Sequence[str], None] = "902b3ccc9cfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.CheckConstraint("json_valid(config)", name="ck_templates_config_json_valid"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_type", name="uq_templates_device_type"),
        sa.UniqueConstraint("filename", name="uq_templates_filename"),
    )
    with op.batch_alter_table("templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_templates_device_type"), ["device_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_templates_device_type"))

    op.drop_table("templates")
    # ### end Alembic commands ###
