"""Fix baudrate and parity columns

Revision ID: 9c6c9211132f
Revises: 040ec586f8c3
Create Date: 2026-04-18 11:23:14.547416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c6c9211132f"
down_revision: Union[str, Sequence[str], None] = "040ec586f8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bus", schema=None) as batch_op:
        batch_op.add_column(sa.Column("baudrate", sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column("parity", sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bus", schema=None) as batch_op:
        batch_op.drop_column("parity")
        batch_op.drop_column("baudrate")

    # ### end Alembic commands ###
