"""Update devices table

Revision ID: c66a10104ead
Revises: 92acb144340a
Create Date: 2026-06-28 12:56:53.237423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c66a10104ead"
down_revision: Union[str, Sequence[str], None] = "92acb144340a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("config", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("itf_name", sa.String(), nullable=True))
        batch_op.drop_column("model")

    op.execute("UPDATE devices SET config = '{}' WHERE config IS NULL")
    op.execute("UPDATE devices SET itf_name = 'serial' WHERE itf_name IS NULL")

    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.alter_column("config", nullable=False)
        batch_op.alter_column("itf_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("model", sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column("config")
        batch_op.drop_column("itf_name")


# ### end Alembic commands ###
